Added different level of logs throughout whole codebase.
DostEducation/RP_IVR_analytics pull request #342
Opened 2023-02-03 14:33 UTC by Satendra-SR

#338 

### Please complete the following steps and check these boxes before filing your PR:

### Types of changes

- [ ] Bug fix (a change which fixes an issue)
- [ ] New feature (a change which adds functionality)

### Short description of what this resolves:

### Checklist:

- [ ] I have performed a self-review of my own code.
- [ ] The code follows the style guidelines of this project.
- [ ] The code changes are passing the CI checks
- [ ] I have documented my code wherever required.
- [ ] The changes requires a change to the documentation.
- [ ] I have updated the documentation based on the my changes.

2023-02-10 13:49 UTC, GauravGusain98 requested changes

2023-02-10 13:49 UTC, GauravGusain98 commented on api/services/contact_fields_mapping_service.py
> +                    )
This is not required

2023-02-10 13:49 UTC, GauravGusain98 commented on api/services/program_sequence_service.py
> +                logger.error("No user program details found")
Can we print user_id as well

2023-02-10 13:49 UTC, GauravGusain98 commented on api/services/prompt_service.py
> +            )
Not needed

2023-02-10 13:49 UTC, GauravGusain98 commented on api/services/prompt_service.py
> +                        )
Not nededed

2023-02-11 10:32 UTC, Satendra-SR commented on api/services/contact_fields_mapping_service.py
> +                    )
Removed

2023-02-11 10:32 UTC, Satendra-SR commented on api/services/program_sequence_service.py
> +                logger.error("No user program details found")
Added

2023-02-11 10:32 UTC, Satendra-SR commented on api/services/prompt_service.py
> +            )
Removed

2023-02-11 10:32 UTC, Satendra-SR commented on api/services/prompt_service.py
> +                        )
Removed

2023-02-12 07:35 UTC, GauravGusain98 requested changes

2023-02-12 07:35 UTC, GauravGusain98 commented on api/helpers/db_helper.py
> +            f"Error while fetching partner id by system phone {system_phone}: {e}"
```suggestion
            f"Error while fetching partner id by system phone {system_phone}. Error message: {e}"
```

2023-02-12 07:35 UTC, GauravGusain98 commented on api/helpers/db_helper.py
> +            f"Error occurred while commiting the data in the database. Error Message:  {e}"
```suggestion
            f"Error occurred while committing the data in the database. Error message:  {e}"
```

2023-02-12 07:35 UTC, GauravGusain98 commented on api/helpers/prompt_helper.py
> +        logger.error(f"Error while splitting prompt by hyphen: {e}")
```suggestion
        logger.error(f"Error while splitting prompt '{data}' by hyphen. Error message: {e}")
```

2023-02-12 07:35 UTC, GauravGusain98 commented on api/helpers/prompt_helper.py
> +        logger.error(f"Error while splitting prompt by underscore: {e}")
```suggestion
        logger.error(f"Error while splitting prompt '{data}' by underscore. Error message: {e}")
```

2023-02-12 07:35 UTC, GauravGusain98 commented on api/helpers/prompt_helper.py
> +        logger.error(f"Error while getting program prompt id: {e}")
This try and except is not needed.

2023-02-12 07:35 UTC, GauravGusain98 commented on api/helpers/prompt_helper.py
> +            f"An error occurred while getting data type for column {column_name} in table {table_name}: {e}"
```suggestion
            f"An error occurred while getting data type for column {column_name} in table {table_name}. Error message: {e}"
```

2023-02-12 07:35 UTC, GauravGusain98 commented on api/models/contact_fields_mapping.py
> +            logger.error(f"Exception occurred while getting field name: {e}")
```suggestion
            logger.error(f"Exception occurred while fetching contact field mapping using field name: {field_name} and value: {field_value}. Error message: {e}")
```

2023-02-12 07:35 UTC, GauravGusain98 commented on api/models/contact_fields_mapping.py
> +            logger.error(f"Exception occurred while getting group name: {e}")
```suggestion
            logger.error(f"Exception occurred while fetching contact field mapping using group name {contact_groups}. Erorr message: {e}")
```

2023-02-12 07:35 UTC, GauravGusain98 commented on api/models/user_program.py
> +                f"Failed to fetch the latest active user program for user_id {user_id}: {e}"
```suggestion
                f"Failed to fetch the latest active user program for user_id {user_id}. Error message: {e}"
```

2023-02-12 07:35 UTC, GauravGusain98 commented on api/models/user_program.py
> +                f"Failed to update user program details for user_program_id {user_program_details.id}: {e}"
```suggestion
                f"Failed to update user program details for user_program_id {user_program_details.id}. Error message: {e}"
```

2023-02-12 07:35 UTC, GauravGusain98 commented on api/models/user_program.py
> +                f"Error occurred while fetching latest user program for user_id: {user_id}. Error: {e}"
```suggestion
                f"Error occurred while fetching latest user program for user_id: {user_id}. Error message: {e}"
```

2023-02-12 07:35 UTC, GauravGusain98 commented on api/services/call_log_service.py
> +                f"Failed to fetch flow run details for user phone {self.user_phone}: {e}"
```suggestion
                f"Failed to fetch flow run details for user phone {self.user_phone}. Error message: {e}"
```

2023-02-12 07:35 UTC, GauravGusain98 commented on api/services/call_log_service.py
> +            logger.error(f"Failed to create call log for {self.user_phone}: {e}")
```suggestion
            logger.error(f"Failed to create call log for {self.user_phone}. Error message: {e}")
```

2023-02-12 07:35 UTC, GauravGusain98 commented on api/services/call_log_service.py
> +                f"Failed to update call log for {self.user_phone}: {e}", exc_info=True
What the use of `exc_info=True`. And why we have not used it on other places?

2023-02-12 07:35 UTC, GauravGusain98 commented on api/services/contact_fields_mapping_service.py
> +                f"Error occurred while handling custom field mapping for {self.user_phone}. Exception: {e}"
Lets make the language consistent
```suggestion
                f"Error occurred while handling custom field mapping for {self.user_phone}. Error message: {e}"
```

2023-02-12 07:35 UTC, GauravGusain98 commented on api/services/contact_fields_mapping_service.py
> +                f"Error occurred while handling custom field mapping for {self.user_phone}. Exception: {e}"
```suggestion
                f"Error occurred while handling custom field mapping for {self.user_phone}. Error message: {e}"
```

2023-02-12 07:35 UTC, GauravGusain98 commented on api/services/contact_fields_mapping_service.py
> +                f"Exception occurred while processing contact field data for {self.user_phone}. Error: {e}"
```suggestion
                f"Exception occurred while processing contact field data for {self.user_phone}. Error message: {e}"
```

2023-02-12 07:35 UTC, GauravGusain98 commented on api/services/contact_fields_mapping_service.py
> +                f"Exception occurred while processsing contact group data for {self.user_phone}. Error: {e}"
```suggestion
                f"Exception occurred while processing contact group data for {self.user_phone}. Error message: {e}"
```

2023-02-12 07:35 UTC, GauravGusain98 commented on api/services/contact_fields_mapping_service.py
> +                f"Exception occurred while updating mapped fields for {self.user_phone}. Error: {e}"
```suggestion
                f"Exception occurred while updating mapped fields for {self.user_phone}. The column name is {column_name} and the value is {mapped_table_column_value}. Error: {e}"
```

2023-02-12 07:35 UTC, GauravGusain98 commented on api/services/program_sequence_service.py
>                  # Need to log this
Remove this comment

2023-02-12 07:35 UTC, GauravGusain98 commented on api/services/program_sequence_service.py
> +                f"Exception occured while getting program sequence id for {self.user_phone}. Error: {e}"
```suggestion
                f"Exception occured while getting program sequence id for {self.user_phone}. Error message: {e}"
```

2023-02-12 07:35 UTC, GauravGusain98 commented on api/services/prompt_service.py
> +                f"Exception occurred while handling prompt mapping for user phone {self.user_phone}: {e}"
```suggestion
                f"Exception occurred while handling prompt mapping for user phone {self.user_phone}. Error message {e}"
```

2023-02-12 07:35 UTC, GauravGusain98 commented on api/services/prompt_service.py
> +                f"Failed to process mapped fields for user phone {self.user_phone}. Error:{e}"
```suggestion
                f"Failed to process mapped fields for prompt value '{prompt_response_value}' and for user phone {self.user_phone}. Error message:{e}"
```

2023-02-12 07:35 UTC, GauravGusain98 commented on api/services/prompt_service.py
> +                f"Exception occurred while updating mapped fields for {self.user_phone}: {e}"
```suggestion
                f"Exception occurred while updating mapped fields for prompt value = {prompt_response_value} and for {self.user_phone}. Error message {e}"
```

2023-02-12 07:35 UTC, GauravGusain98 commented on api/services/prompt_service.py
> +                f"Keypress value by {self.user_phone} is not an integer. Error: {e}"
```suggestion
                f"Keypress value by {self.user_phone} is not an integer. Error message: {e}"
```

2023-02-12 07:35 UTC, GauravGusain98 commented on api/services/registration_service.py
> +                f"Failed to handle registration for {self.user_phone}. Error: {e}"
```suggestion
                f"Failed to handle registration for {self.user_phone}. Error messager: {e}"
```

2023-02-12 07:35 UTC, GauravGusain98 commented on api/services/registration_service.py
> +                    f"Failed to save registration data for user with phone {self.user_phone}. Error: {e}"
```suggestion
                    f"Failed to save registration data for user with phone {self.user_phone}. Error message: {e}"
```

2023-02-12 07:35 UTC, GauravGusain98 commented on api/services/registration_service.py
> +                    f"Failed to update registration for {self.user_phone}: {e}"
```suggestion
                    f"Failed to update registration for {self.user_phone}. Error message: {e}"
```

2023-02-12 07:35 UTC, GauravGusain98 commented on api/services/transaction_log_service.py
> +            logger.error(f"Error while creating new webhook log: {e}")
```suggestion
            logger.error(f"Error while creating new webhook log. Webhook: {jsonData}. Error message: {e}")
```

2023-02-12 07:35 UTC, GauravGusain98 commented on api/services/transaction_log_service.py
> +            logger.error(f"Error while marking webhook log as processed: {e}")
```suggestion
            logger.error(f"Error while marking webhook log as processed. Error message: {e}")
```

2023-02-12 07:35 UTC, GauravGusain98 commented on api/services/transaction_log_service.py
> +            logger.error(f"Error while retrieving failed webhook transaction logs: {e}")
```suggestion
            logger.error(f"Error while retrieving failed webhook transaction logs. Error message: {e}")
```

2023-02-12 07:35 UTC, GauravGusain98 commented on main.py
> +                    logger.error("[ERROR] Error processing the payload")
```suggestion
                    logger.error("Error processing the payload: {josnData}")
```

2023-02-12 07:35 UTC, GauravGusain98 commented on main.py
> +                    logger.warning("[ERROR] Contact not found in the payload")
Not use this if we are not using it on other logs
```suggestion
                    logger.warning("Contact not found in the payload")
```

2023-02-12 07:35 UTC, GauravGusain98 commented on main.py
> +        logger.error("[ERROR] An unexpected error occurred: %s" % e)
```suggestion
        logger.error(f"An unexpected error occurred. Error message: {e}" )
```

2023-02-12 07:35 UTC, GauravGusain98 commented on main.py
> +        logger.info("[INFO] Successfully processed the failed log")
No needed

2023-02-12 07:35 UTC, GauravGusain98 commented on main.py
> +            logger.error("[ERROR] No 'contact' key found in the input JSON data.")
```suggestion
            logger.error("No 'contact' key found in the input JSON data. {josnData}")
```

2023-02-12 07:35 UTC, GauravGusain98 commented on main.py
> +        logger.error(f"[ERROR] Exception Occured while handeling payload: {e}")
```suggestion
        logger.error(f"Exception occurred while handling payload: {e}")
```

2023-02-12 07:35 UTC, GauravGusain98 commented on main.py
> +    logger.info("[INFO] Payload processing completed successfully.")
Not needed

2023-02-12 10:04 UTC, Satendra-SR commented on api/helpers/prompt_helper.py
> +        logger.error(f"Error while getting program prompt id: {e}")
Removed

2023-02-12 10:04 UTC, Satendra-SR commented on main.py
> +        logger.info("[INFO] Successfully processed the failed log")
Removed

2023-02-12 10:05 UTC, Satendra-SR commented on main.py
> +    logger.info("[INFO] Payload processing completed successfully.")
Removed

2023-02-12 12:15 UTC, GauravGusain98 approved these changes

2023-02-12 12:17 UTC, merged