Bugfix/adding function to mark user completed
DostEducation/RP_IVR_analytics pull request #377
Opened 2023-04-25 07:21 UTC by vivek-kumar-pandey

### Please complete the following steps and check these boxes before filing your PR:

### Types of changes

- [x] Bug fix (a change which fixes an issue)
- [ ] New feature (a change which adds functionality)

### Short description of what this resolves:

The functionality to mark users as completed after their program completes was missing so adding them back.

### Checklist:

- [x] I have performed a self-review of my own code.
- [x] The code follows the style guidelines of this project.
- [ ] The code changes are passing the CI checks
- [ ] I have documented my code wherever required.
- [ ] The changes requires a change to the documentation.
- [ ] I have updated the documentation based on the my changes.

2023-04-25 07:47 UTC, Satendra-SR requested changes
One suggestion else looks good.

2023-04-25 07:47 UTC, Satendra-SR commented on api/services/user_program_service.py
> +            )
While marking the user_program status as **completed** we need to update the end_date of the user_program also.

2023-04-28 10:11 UTC, GauravGusain98 approved these changes
LGTM

2023-04-28 10:17 UTC, Satendra-SR approved these changes
Looks fine.

2023-04-28 14:04 UTC, merged